### ISSUE TITLE
wq 1.0 checklist

### ISSUE THREAD

**Issue by sheppard** [wq/wq#22]
See also the release notes for [wq.db 0.8.0](https://github.com/wq/wq.db/releases/v0.8.0), [wq 0.8.0](https://github.com/wq/wq/releases/v0.8.0), and [wq 0.8.5](https://github.com/wq/wq/releases/v0.8.5).
#### Improve "Getting Started" workflow
- [x] Tool to auto-generate Mustache templates (wq/wq-django-template#18)
- [x] Document process for configuring surveys with various field/question types (#18)
- [x] <strike>Better cross-platform support for build script (wq/wq-django-template#20) - move to 1.1</strike>
- [x] <strike>Finish documentation for Windows and OS X installation - move to 1.1</strike>
- [x] <strike>Configure & promote Slack/Gitter account (#20) - move to 1.1</strike>
- [x] <strike>Comparison to ODK and other platforms (#6) - move to 1.1</strike>
- [x] Detailed project profiles with implementation notes
- [x] <strike>Debugging workflow (#2) - move to 1.1</strike>
- [x] `wq` command documentation (#17)
- [x] <strike>Adding custom screens, difference between server-only and shared views - move to 1.1</strike>
#### Patterns API overhaul
- [x] remove all references to wq.db.patterns from wq.db.rest (wq/wq.db#35)
- [x] don't register patterns attachment models by default? (wq/wq.db#46)
- [x] remove patterns.admin code? (wq/wq.db#38)
- [x] remove support for "classic" form style (wq/wq.db#33)
- [x] fully JSON-based attachment configuration (wq/wq.app#38)
- [x] Expand documentation
  - [x] Document [vera](https://wq.io/vera), noting similarity and differences with other "patterns" (wq/wq#7)
  - [x] Document process for implementing custom patterns (wq/wq#21)
  - [x] <strike>Rename `patterns` to something more descriptive (nested forms?)</strike>
  - [x] High level [overview](https://wq.io/docs/eav-vs-relational) on choosing whether to use E(R)AV versus normal relational fields.
  - [x] [Species Tracker](https://github.com/powered-by-wq/species.wq.io)-style demo and tutorial: [Try WQ](https://github.com/powered-by-wq/try.wq.io)
#### [wq.app cleanup](https://github.com/wq/wq.app/milestones/1.0)
- [x] Unit tests (wq/wq.app#13)
- [x] <strike>AJAX blob support in android 4.3 and earlier (wq/wq.app#51)</strike>
- [x] clarify pagination story (wq/wq.app#47)
- [x] <strike>better offline detection (wq/wq.app#33)</strike>
#### Third Party Library Updates
- [x] Drop Django 1.7 support in favor of Django 1.9.  Remove all backwards-compatibility hacks (wq/wq.db#51).
  - [x] wq.db: update template engine to work with Django 1.8 TEMPLATE setting (wq/wq.db#48)
  - [x] <strike>vera: use Django's `field.clone()`</strike>
  - [x] Update wq.start template to use Django 1.8-style settings (wq/wq-django-template#7)
- [x] wq.app: Update to latest JavaScript libraries, if ready
  - [x] <strike>[jQuery Mobile 1.5](http://jquerymobile.com/roadmap/)</strike> - Not ready yet
  - [x] [Leaflet 1.0](http://leafletjs.com/2015/07/15/leaflet-1.0-beta1-released.html)
  - [x] [d3.js 4.0](https://github.com/d3)
- [x] wq.app: contribute select [wq/store.js](https://wq.io/docs/store-js) enhancements back to `localForage`
  - [x] <strike>Ability to convert `File` into `Blob` (mozilla/localForage#414) - move to 1.1</strike>
  - [x] Ability to handle nested `Blob`s within other objects (mozilla/localForage#380)
- [x] wq.db: extract more functionality for general use
  - [x] Move [chart](https://wq.io/docs/chart) code to DRP (wq/django-rest-pandas#17)
    - [x] Remove remaining chart code
  - [x] Extract Mustache template engine into standalone library ([django_mustache](https://github.com/wq/django-mustache))
  - [x] Extract [`NaturalKeyModel`](https://github.com/wq/wq.db/blob/master/patterns/base/models.py) into standalone library (wq/wq.db#50)
  - [x]  contribute HTML JSON form support to DRF or standalone library (tomchristie/django-rest-framework#2682)
